/**
* @file			oscilator.h
*	@author		Nahum Budin
*	@date		13-Sep-2024
*	@version	1.0
*	
*	@brief		Provides the Oscilators related API
*	
*	Based on libAdjHeartModSynth_1.h Ver 1.3 9-Jan-2021
*/

#pragma once

#define _SYNTH_MAX_NUM_OF_VOICES			48
#if (_SYNTH_MAX_NUM_OF_CORE_VOICES > 64)
Error - must be no more than 64
#endif

#define _SYNTH_MAX_NUM_OF_CORES				8
#if (_SYNTH_MAX_NUM_OF_CORES > 8)
		Error -
		must be no more than 8
#endif
	
#define _SYNTH_MAX_NUM_OF_PROGRAMS		_PROGRAM_18 + 1
#if (_SYNTH_MAX_NUM_OF_PROGRAMS > _PROGRAM_18 + 1)
	Error -
	must be no more than PROGRAM_18 + 1
#endif
		
#define _NUM_OF_PRESETS						5
	
#define	_NUM_OF_HARMONIES					9

#define _OSC_MAX_FREQUENCY					12543.8539514160f	// MIDI G11
#define _OSC_MIN_FREQUENCY					0.1f				// LFO 8.1757989156f	// MIDI C1

#define _OSC_WAVEFORM_SINE					0
#define _OSC_WAVEFORM_SQUARE				1
#define _OSC_WAVEFORM_PULSE					2
#define _OSC_WAVEFORM_TRIANGLE				3
#define _OSC_WAVEFORM_SAMPHOLD				4

#define _OSC_DETUNE_MAX_OCTAVE				6
#define _OSC_DETUNE_MIN_OCTAVE				-6
#define _OSC_DETUNE_MAX_SEMITONES			11
#define _OSC_DETUNE_MIN_SEMITONES			-11
#define _OSC_DETUNE_MAX_CENTS				7.5f
#define _OSC_DETUNE_MIN_CENTS				-7.5f
#define _OSC_DETUNE_CENTS_FACTORIAL			0.25f

#define	_NUM_OF_HARMONIES					9

#define _OSC_UNISON_MODE_12345678			0
#define _OSC_UNISON_MODE_HAMMOND			1
#define _OSC_UNISON_MODE_OCTAVES			2
#define _OSC_UNISON_MODE_C_CHORD			3
#define _OSC_UNISON_MODE_Cm_CHORD			4
#define _OSC_UNISON_MODE_C7_CHORD			5
#define _OSC_UNISON_MODE_Cm7_CHORD			6

#define _NUM_OF_HARMONIZING_FREQUENCIES		13
#define _MAX_HARMONIES_DISTORTION_FACTOR	3.0f
#define _MIN_HARMONIES_DISTORTION_FACTOR	1.0f
#define _MAX_HARMONIES_DETUNE_FACTOR		0.08f
#define _MIN_HARMONIES_DETUNE_FACTOR		0.0f

#define _KARPLUS_STRONG_STATE_STEADY_OUTPUT				0
#define _KARPLUS_STRONG_STATE_STEADY_BEGIN_NEXT			1
#define _KARPLUS_STRONG_STATE_PLAYING					2

#define _KARPLUS_STRONG_MIN_FREQ						27.5f			// MIDI A0
#define _KARPLUS_STRONG_MAX_FREQ						4186.0f			// MIDI C8

#define _KARPLUS_STRONG_MAX_PLUCK_DAMPING				0.9f
#define _KARPLUS_STRONG_MIN_PLUCK_DAMPING				0.1f

#define _KARPLUS_STRONG_MAX_PLUCK_DAMPING_VARIATION		0.5f
#define _KARPLUS_STRONG_MIN_PLUCK_DAMPING_VARIATION		0.0f

#define _KARPLUS_STRONG_MAX_STRING_DAMPING				0.7f
#define _KARPLUS_STRONG_MIN_STRING_DAMPING				0.1f

#define _KARPLUS_STRONG_MAX_STRING_DAMPING_VARIATION	0.5f
#define _KARPLUS_STRONG_MIN_STRING_DAMPING_VARIATION	0.0f

#define _KARPLUS_STRONG_MAX_CHARACTER_VARIATION			1.0f
#define _KARPLUS_STRONG_MIN_CHARACTER_VARIATION			0.0f

#define _KARPLUS_STRONG_MAX_DECAY						0.999f
#define _KARPLUS_STRONG_MIN_DECAY						0.9f



#define _WHITE_NOISE				0
#define _PINK_NOISE					1
#define _BROWN_NOISE				2

#define _DISTORTION_MAX_DRIVE		1.f
#define _DISTORTION_MIN_DRIVE		0.f
#define _DISTORTION_MAX_RANGE		100.f
#define _DISTORTION_MIN_RANGE		1.f
#define _DISTORTION_MAX_BLEND		1.f
#define _DISTORTION_MIN_BLEND		0.f

#define _FILTER_MIN_CENTER_FREQ		20.0f
#define _FILTER_MIN_Q				0.7f
#define _FILTER_MAX_Q				5.0f

#define _FILTER_BAND_LPF			0
#define _FILTER_BAND_HPF			1
#define _FILTER_BAND_BPF			2
#define _FILTER_BAND_PASS_ALL		3

#define _CONTROL_SUB_SAMPLING		16

#define _MOD_LFO_MIN_FREQ			0.1f
#define _MOD_LFO_MAX_FREQ			10.0f

#define _NUM_OF_LFOS				5
#define _NUM_OF_LFO_DELAY_OPTIONS	5
#define _LFO_NONE					0
#define _LFO_1						1
#define _LFO_2						2
#define _LFO_3						3
#define _LFO_4						4
#define _LFO_5						5
#define _LFO_1_DELAYED_500MS		10
#define _LFO_2_DELAYED_500MS		11
#define _LFO_3_DELAYED_500MS		12
#define _LFO_4_DELAYED_500MS		13
#define _LFO_5_DELAYED_500MS		14

#define _LFO_1_DELAYED_1000MS		20
#define _LFO_2_DELAYED_1000MS		21
#define _LFO_3_DELAYED_1000MS		22
#define _LFO_4_DELAYED_1000MS		23
#define _LFO_5_DELAYED_1000MS		24

#define _LFO_1_DELAYED_1500MS		30
#define _LFO_2_DELAYED_1500MS		31
#define _LFO_3_DELAYED_1500MS		32
#define _LFO_4_DELAYED_1500MS		33
#define _LFO_5_DELAYED_1500MS		34

#define _LFO_1_DELAYED_2000MS		40
#define _LFO_2_DELAYED_2000MS		41
#define _LFO_3_DELAYED_2000MS		42
#define _LFO_4_DELAYED_2000MS		43
#define _LFO_5_DELAYED_2000MS		44


#define _NUM_OF_ADSRS				5
#define _ENV_NONE					0
#define _ENV_1						1
#define _ENV_2						2
#define _ENV_3						3
#define _ENV_4						4
#define _ENV_5						5


// Maximum Attack time in seconds
#define ADSR_MAX_ATTACK_TIME_SEC	2.0f	
// Maximum Decay time in seconds 
#define ADSR_MAX_DECAY_TIME_SEC		5.0f	
// Maximum Release time in seconds
#define ADSR_MAX_RELEASE_TIME_SEC	10.0f
	
#define _PROGRAM_0					0
#define _PROGRAM_1					1
#define _PROGRAM_2					2
#define _PROGRAM_3					3
#define _PROGRAM_4					4
#define _PROGRAM_5					5
#define _PROGRAM_6					6
#define _PROGRAM_7					7
#define _PROGRAM_8					8
#define _PROGRAM_9					9
#define _PROGRAM_10					10
#define _PROGRAM_11					11
#define _PROGRAM_12					12
#define _PROGRAM_13					13
#define _PROGRAM_14					14
#define _PROGRAM_15					15
#define _PROGRAM_16					16		// Scetch 1
#define _PROGRAM_17					17
#define _PROGRAM_18					18
	
#define _SYNTH_MAX_NUM_OF_PROGRAMS		_PROGRAM_18 + 1
#if (_SYNTH_MAX_NUM_OF_PROGRAMS > _PROGRAM_18 + 1)
	Error -
	must be no more than PROGRAM_18 + 1
#endif
		
#define _SYNTH_NUM_OF_PROGRAMS						_SYNTH_MAX_NUM_OF_PROGRAMS

#define _MIDI_MIXER_CHAN_1							_PROGRAM_0
#define _MIDI_MIXER_CHAN_2							_PROGRAM_1
#define _MIDI_MIXER_CHAN_3							_PROGRAM_2
#define _MIDI_MIXER_CHAN_4							_PROGRAM_3
#define _MIDI_MIXER_CHAN_5							_PROGRAM_4
#define _MIDI_MIXER_CHAN_6							_PROGRAM_5
#define _MIDI_MIXER_CHAN_7							_PROGRAM_6
#define _MIDI_MIXER_CHAN_8							_PROGRAM_7
#define _MIDI_MIXER_CHAN_9							_PROGRAM_8
#define _MIDI_MIXER_CHAN_10							_PROGRAM_9
#define _MIDI_MIXER_CHAN_11							_PROGRAM_10
#define _MIDI_MIXER_CHAN_12							_PROGRAM_11
#define _MIDI_MIXER_CHAN_13							_PROGRAM_12
#define _MIDI_MIXER_CHAN_14							_PROGRAM_13
#define _MIDI_MIXER_CHAN_15							_PROGRAM_14
#define _MIDI_MIXER_CHAN_16							_PROGRAM_15
#define _SKETCH_PROGRAM_1							_PROGRAM_16
#define _SKETCH_PROGRAM_2							_PROGRAM_17
#define _SKETCH_PROGRAM_3							_PROGRAM_18
	
	
#define _HAMMOND_PERCUSION_MODE_OFF					0
#define _HAMMOND_PERCUSION_MODE_2ND_SOFT_SLOW		1
#define _HAMMOND_PERCUSION_MODE_2ND_SOFT_FAST		2
#define _HAMMOND_PERCUSION_MODE_2ND_NORM_SLOW		3
#define _HAMMOND_PERCUSION_MODE_2ND_NORM_FAST		4
#define _HAMMOND_PERCUSION_MODE_3RD_SOFT_SLOW		5
#define _HAMMOND_PERCUSION_MODE_3RD_SOFT_FAST		6
#define _HAMMOND_PERCUSION_MODE_3RD_NORM_SLOW		7
#define _HAMMOND_PERCUSION_MODE_3RD_NORM_FAST		8
	
	
#define _AMP_LEVEL									500
#define _AMP_PAN									501
#define _AMP_ENV_MOD_ENABLE							502
#define _AMP_PAN_MOD_LFO							503
#define _AMP_PAN_MOD_LFO_LEVEL						504
#define _AMP_FIXED_LEVELS							505
#define _AMP_SEND									506
	
#define _AMP_FIXED_LEVELS_DISABLE					0
#define _AMP_FIXED_LEVELS_ENABLE					1
	
	
#define _KBD_PORTAMENTO_LEVEL						600
#define _KBD_PORTAMENTO_ENABLE						601
#define _KBD_SENSITIVITY_LEVEL						602
#define _KBD_POLY_MODE_LIMIT						603
#define _KBD_POLY_MODE_FIFO							604
#define _KBD_POLY_MODE_REUSE						605
#define _KBD_LOW_SENSITIVITY_LEVEL					606
#define _KBD_SPLIT_POINT							607

#define _KBD_SPLIT_POINT_NONE						0
#define _KBD_SPLIT_POINT_C2							1
#define _KBD_SPLIT_POINT_C3							2
#define _KBD_SPLIT_POINT_C4							3
#define _KBD_SPLIT_POINT_C5							4
	
	
#define _KARPLUS_STRONG_EXCITATION_WAVEFORM			800	
	
#define _KARPLUS_STRONG_EXCITATION_WHITE_NOISE		0
#define _KARPLUS_STRONG_EXCITATION_PINK_NOISE		1
#define _KARPLUS_STRONG_EXCITATION_BROWN_NOISE		2
#define _KARPLUS_STRONG_EXCITATION_SINECHIRP		3
#define _KARPLUS_STRONG_EXCITATION_DECAYEDSINE		4
#define _KARPLUS_STRONG_EXCITATION_SAWTOOTH_WAVE	5
#define _KARPLUS_STRONG_EXCITATION_SQUARE_WAVE		6
	
		
#define _KARPLUS_STRONG_STRING_DUMP_CALC_MODE		801	
	
#define _KARPLUS_STRONG_STRING_DAMPING_CALC_DIRECT	0
#define _KARPLUS_STRONG_STRING_DAMPING_CALC_MAGIC	1
		
#define _KARPLUS_STRONG_STRING_DAMPING				802
#define _KARPLUS_STRONG_STRING_DAMPING_VARIATION	803
#define _KARPLUS_STRONG_PLUCK_DAMPING				804
#define _KARPLUS_STRONG_PLUCK_DAMPING_VARIATION		805
#define _KARPLUS_STRONG_ON_DECAY					806
#define _KARPLUS_STRONG_OFF_DECAY					807
#define _KARPLUS_STRONG_EXCITATION_WAVEFORM_VARIATIONS 808
#define _KARPLUS_STRONG_ENABLE						809	
	
#define _SYNTH_VOICE_1								0
	
#define _PLAY_MODE									1000
#define _PLAY_MODE_POLY								0
#define _PLAY_MODE_SOLO								1
#define _PLAY_MODE_MIDI								2
	
	
#define _BAND_EQUALIZER_BAND_31_LEVEL				1200
#define _BAND_EQUALIZER_BAND_62_LEVEL				1201
#define _BAND_EQUALIZER_BAND_125_LEVEL				1202
#define _BAND_EQUALIZER_BAND_250_LEVEL				1203
#define _BAND_EQUALIZER_BAND_500_LEVEL				1204
#define _BAND_EQUALIZER_BAND_1K_LEVEL				1205
#define _BAND_EQUALIZER_BAND_2K_LEVEL				1206
#define _BAND_EQUALIZER_BAND_4K_LEVEL				1207
#define _BAND_EQUALIZER_BAND_8K_LEVEL				1208
#define _BAND_EQUALIZER_BAND_16K_LEVEL				1209

#define _BAND_EQUALIZER_PRESET						1220		// 0?
#define _BAND_EQUALIZER_SET_ALL_ZERO				1221		// 1?
	
	
#define _PAD_DETUNE_OCTAVE							1500
#define _PAD_DETUNE_SEMITONES						1501
#define _PAD_DETUNE_CENTS							1502
#define _PAD_FILTER_SEND_1							1503
#define _PAD_FILTER_SEND_2							1504
#define _PAD_ENABLE									1505

#define _PAD_FREQ_MOD_LFO							1506
#define _PAD_FREQ_MOD_LFO_LEVEL						1507
#define _PAD_FREQ_MOD_ENV							1508
#define _PAD_FREQ_MOD_ENV_LEVEL						1509
#define _PAD_AMP_MOD_LFO							1510
#define _PAD_AMP_MOD_LFO_LEVEL						1511
#define _PAD_AMP_MOD_ENV							1512
#define _PAD_AMP_MOD_ENV_LEVEL						1513
		
#define _PAD_HARMONY_LEVEL_1						1520
#define _PAD_HARMONY_LEVEL_2						1521
#define _PAD_HARMONY_LEVEL_3						1522
#define _PAD_HARMONY_LEVEL_4						1523
#define _PAD_HARMONY_LEVEL_5						1524
#define _PAD_HARMONY_LEVEL_6						1525
#define _PAD_HARMONY_LEVEL_7						1526
#define _PAD_HARMONY_LEVEL_8						1527
#define _PAD_HARMONY_LEVEL_9						1528
#define _PAD_HARMONY_LEVEL_10						1529

#define _PAD_QUALITY								1530

#define _PAD_QUALITY_32K							0
#define _PAD_QUALITY_64K							1
#define _PAD_QUALITY_128K							2
#define _PAD_QUALITY_256K							3
#define _PAD_QUALITY_512K							4
#define _PAD_QUALITY_1024K							5

#define _PAD_SHAPE									1531		
		
#define _PAD_SHAPE_RECTANGULAR						0
#define _PAD_SHAPE_GAUSSIAN							1
#define _PAD_SHAPE_DOUBLE_EXP						2
		
#define _PAD_BASE_NOTE								1532

#define _PAD_BASE_NOTE_C2							0
#define _PAD_BASE_NOTE_G2							1
#define _PAD_BASE_NOTE_C3							2
#define _PAD_BASE_NOTE_G3							3
#define _PAD_BASE_NOTE_C4							4
#define _PAD_BASE_NOTE_G4							5
#define _PAD_BASE_NOTE_C5							6
#define _PAD_BASE_NOTE_G5							7
#define _PAD_BASE_NOTE_C6							8
#define _PAD_BASE_NOTE_G6							9
		
#define _PAD_BASE_WIDTH								1533
#define _PAD_GENERATE								1534
#define _PAD_DETUNE									1535

#define _PAD_SHAPE_CUTOFF							1540		
		
#define _PAD_SHAPE_CUTOFF_FULL						0
#define _PAD_SHAPE_CUTOFF_UPPER						1
#define _PAD_SHAPE_CUTOFF_LOWER						2
		
#define _SEQUENCER_START_RECORDING					1600
#define _SEQUENCER_STOP_RECORDING					1601


