/**
* @file			oscilator.h
*	@author		Nahum Budin
*	@date		13-Sep-2024
*	@version	1.0
*	
*	@brief		Provides the Oscilators related API
*	
*	Based on libAdjHeartModSynth_1.h Ver 1.3 9-Jan-2021
*/

#pragma once

#define _OSC_MAX_FREQUENCY					12543.8539514160f	// MIDI G11
#define _OSC_MIN_FREQUENCY					0.1f				// LFO 8.1757989156f	// MIDI C1

#define _OSC_WAVEFORM_SINE					0
#define _OSC_WAVEFORM_SQUARE				1
#define _OSC_WAVEFORM_PULSE					2
#define _OSC_WAVEFORM_TRIANGLE				3
#define _OSC_WAVEFORM_SAMPHOLD				4

#define _OSC_DETUNE_MAX_OCTAVE				6
#define _OSC_DETUNE_MIN_OCTAVE				-6
#define _OSC_DETUNE_MAX_SEMITONES			11
#define _OSC_DETUNE_MIN_SEMITONES			-11
#define _OSC_DETUNE_MAX_CENTS				7.5f
#define _OSC_DETUNE_MIN_CENTS				-7.5f
#define _OSC_DETUNE_CENTS_FACTORIAL			0.25f

#define	_NUM_OF_HARMONIES					9

#define _OSC_UNISON_MODE_12345678			0
#define _OSC_UNISON_MODE_HAMMOND			1
#define _OSC_UNISON_MODE_OCTAVES			2
#define _OSC_UNISON_MODE_C_CHORD			3
#define _OSC_UNISON_MODE_Cm_CHORD			4
#define _OSC_UNISON_MODE_C7_CHORD			5
#define _OSC_UNISON_MODE_Cm7_CHORD			6

#define _NUM_OF_HARMONIZING_FREQUENCIES		13
#define _MAX_HARMONIES_DISTORTION_FACTOR	3.0f
#define _MIN_HARMONIES_DISTORTION_FACTOR	1.0f
#define _MAX_HARMONIES_DETUNE_FACTOR		0.08f
#define _MIN_HARMONIES_DETUNE_FACTOR		0.0f

#define _KARPLUS_STRONG_STATE_STEADY_OUTPUT				0
#define _KARPLUS_STRONG_STATE_STEADY_BEGIN_NEXT			1
#define _KARPLUS_STRONG_STATE_PLAYING					2

#define _KARPLUS_STRONG_MIN_FREQ						27.5f			// MIDI A0
#define _KARPLUS_STRONG_MAX_FREQ						4186.0f			// MIDI C8

#define _KARPLUS_STRONG_MAX_PLUCK_DAMPING				0.9f
#define _KARPLUS_STRONG_MIN_PLUCK_DAMPING				0.1f

#define _KARPLUS_STRONG_MAX_PLUCK_DAMPING_VARIATION		0.5f
#define _KARPLUS_STRONG_MIN_PLUCK_DAMPING_VARIATION		0.0f

#define _KARPLUS_STRONG_MAX_STRING_DAMPING				0.7f
#define _KARPLUS_STRONG_MIN_STRING_DAMPING				0.1f

#define _KARPLUS_STRONG_MAX_STRING_DAMPING_VARIATION	0.5f
#define _KARPLUS_STRONG_MIN_STRING_DAMPING_VARIATION	0.0f

#define _KARPLUS_STRONG_MAX_CHARACTER_VARIATION			1.0f
#define _KARPLUS_STRONG_MIN_CHARACTER_VARIATION			0.0f

#define _KARPLUS_STRONG_MAX_DECAY						0.999f
#define _KARPLUS_STRONG_MIN_DECAY						0.9f

#define _KARPLUS_STRONG_EXCITATION_WAVEFORM			800	
	
#define _KARPLUS_STRONG_EXCITATION_WHITE_NOISE		0
#define _KARPLUS_STRONG_EXCITATION_PINK_NOISE		1
#define _KARPLUS_STRONG_EXCITATION_BROWN_NOISE		2
#define _KARPLUS_STRONG_EXCITATION_SINECHIRP		3
#define _KARPLUS_STRONG_EXCITATION_DECAYEDSINE		4
#define _KARPLUS_STRONG_EXCITATION_SAWTOOTH_WAVE	5
#define _KARPLUS_STRONG_EXCITATION_SQUARE_WAVE		6
		
#define _KARPLUS_STRONG_STRING_DUMP_CALC_MODE		801	
	
#define _KARPLUS_STRONG_STRING_DAMPING_CALC_DIRECT	0
#define _KARPLUS_STRONG_STRING_DAMPING_CALC_MAGIC	1
		
#define _KARPLUS_STRONG_STRING_DAMPING				802
#define _KARPLUS_STRONG_STRING_DAMPING_VARIATION	803
#define _KARPLUS_STRONG_PLUCK_DAMPING				804
#define _KARPLUS_STRONG_PLUCK_DAMPING_VARIATION		805
#define _KARPLUS_STRONG_ON_DECAY					806
#define _KARPLUS_STRONG_OFF_DECAY					807
#define _KARPLUS_STRONG_EXCITATION_WAVEFORM_VARIATIONS 808
#define _KARPLUS_STRONG_ENABLE						809

#define _WHITE_NOISE				0
#define _PINK_NOISE					1
#define _BROWN_NOISE				2

#define _DISTORTION_MAX_DRIVE		1.f
#define _DISTORTION_MIN_DRIVE		0.f
#define _DISTORTION_MAX_RANGE		100.f
#define _DISTORTION_MIN_RANGE		1.f
#define _DISTORTION_MAX_BLEND		1.f
#define _DISTORTION_MIN_BLEND		0.f

#define _FILTER_MIN_CENTER_FREQ		20.0f
#define _FILTER_MIN_Q				0.7f
#define _FILTER_MAX_Q				5.0f

#define _FILTER_BAND_LPF			0
#define _FILTER_BAND_HPF			1
#define _FILTER_BAND_BPF			2
#define _FILTER_BAND_PASS_ALL		3

#define _CONTROL_SUB_SAMPLING		16

#define _MOD_LFO_MIN_FREQ			0.1f
#define _MOD_LFO_MAX_FREQ			10.0f

#define _NUM_OF_LFOS				5
#define _NUM_OF_LFO_DELAY_OPTIONS	5
#define _LFO_NONE					0
#define _LFO_1						1
#define _LFO_2						2
#define _LFO_3						3
#define _LFO_4						4
#define _LFO_5						5
#define _LFO_1_DELAYED_500MS		10
#define _LFO_2_DELAYED_500MS		11
#define _LFO_3_DELAYED_500MS		12
#define _LFO_4_DELAYED_500MS		13
#define _LFO_5_DELAYED_500MS		14

#define _LFO_1_DELAYED_1000MS		20
#define _LFO_2_DELAYED_1000MS		21
#define _LFO_3_DELAYED_1000MS		22
#define _LFO_4_DELAYED_1000MS		23
#define _LFO_5_DELAYED_1000MS		24

#define _LFO_1_DELAYED_1500MS		30
#define _LFO_2_DELAYED_1500MS		31
#define _LFO_3_DELAYED_1500MS		32
#define _LFO_4_DELAYED_1500MS		33
#define _LFO_5_DELAYED_1500MS		34

#define _LFO_1_DELAYED_2000MS		40
#define _LFO_2_DELAYED_2000MS		41
#define _LFO_3_DELAYED_2000MS		42
#define _LFO_4_DELAYED_2000MS		43
#define _LFO_5_DELAYED_2000MS		44


#define _NUM_OF_ADSRS				5
#define _ENV_NONE					0
#define _ENV_1						1
#define _ENV_2						2
#define _ENV_3						3
#define _ENV_4						4
#define _ENV_5						5


// Maximum Attack time in seconds
#define ADSR_MAX_ATTACK_TIME_SEC	2.0f	
// Maximum Decay time in seconds 
#define ADSR_MAX_DECAY_TIME_SEC		5.0f	
// Maximum Release time in seconds
#define ADSR_MAX_RELEASE_TIME_SEC	10.0f


